export enum CommandType {
  Configure = 'configure',
  Profile = 'profile',
  Agent = 'agent',
  Interfaces = 'interfaces',
  Operations = 'operations',
  Login = 'login',
  Interactive = 'interactive',
  Graph = 'graph',
  View = 'View',
  ListJson = 'list-json',
  Tools = 'tools',
  Initialize = 'initialize',
  Dev = 'dev',
  SecretsSync = 'secrets-sync',
  Deploy = 'deploy',
  Restart = 'restart',
  Stop = 'stop',
  Logs = 'logs',
  Invoke = 'invoke',
  Exit = 'exit',
  // Crud
  List = 'list',
  Get = 'get',
  New = 'new',
  Create = 'create',
  Delete = 'delete',
  Update = 'update',
  Edit = 'edit',
  Open = 'open',
}

export const allCommands = [
  ...Object.values(CommandType).filter(
    (cmd) => cmd !== 'interfaces' && cmd !== 'operations',
  ),
  // Add aliases
  'a',
  'c',
  'd',
  'i',
  'l',
  'n',
  'o',
  'g',
  'del',
  'rm',
] as string[];
